% fit_mdlag_v1v2array.m
%
% Description: Fit an mDLAG model to the example V1-V2 dataset.
%
% Author:
%     Evren Gokcen    egokcen@cmu.edu

%% Set up script parameters

set_consts_mdlag_v1v2array;

%% Fit mDLAG model

% Load dataset
load(dataFile);
load('./data/traintestsplit.mat');  % Train and test trials
yDims = dat.yDims;

% Initialize mDLAG model parameters
initParams = init_mdlag(dat.seq(train), ...
                        yDims, xDim_fit, binWidth, ...
                        'prior', prior, ...
                        'randomSeed', randomSeed, ...
                        'saveCcov', saveCcov);
% Optionally segment trials for speedup
seqTrainCut = cutTrials(dat.seq(train), 'segLength', segLength);
% Fit mDLAG model
[estParams,~,trackedParams,flags] ...
    = em_mdlag(initParams, ...
               seqTrainCut, ...
               xDim_fit, ...
               'prior', prior, ...
               'tol', tol, ...
               'maxIters', maxIters, ...
               'freqLB', freqLB, ...
               'freqParam', freqParam, ...
               'learnDelays', learnDelays, ...
               'verbose', verbose, ...
               'minVarFrac', minVarFrac, ...
               'maxDelayFrac', maxDelayFrac, ...
               'maxTauFrac', maxTauFrac, ...
               'pruneX', pruneX, ...
               'saveXcov', saveXcov, ...
               'saveCcov', saveCcov);

%% Create and save appropriate results files

fprintf('Saving results...\n');
save(resultFile_mdlag, 'estParams', 'trackedParams', 'flags');
    