% crossval_noARD_sim1.m
%
% Description: This script cross-validates mDLAG model candidates
%              (with no ARD) for Simulation 1.
%
% Author: 
%     Evren Gokcen    egokcen@cmu.edu

%% Set up script parameters

set_consts_noARD_sim1;

%% Cross-validate models

% Load synthetic data and ground truth
currDataFile = sprintf('%s/%s', dataDir, dataFile);
ws = load(currDataFile);

% Cross-validate DLAG models
baseDir = sprintf('%s/%s', resultDir, noARD_CVDir);
% Change other input arguments as appropriate
numFolds = 4;
maxIters = 1000; % Limit EM iterations during cross-validation for speedup
fitAll = false;  % Don't fit a model to all train data
xDims_grid = zeros(xDim_cv,numGroups+1);
xDims_grid(:,1) = (1:xDim_cv)';
fit_dlag(runIdx, ws.seqTrue, ...
         'baseDir', baseDir, ...
         'binWidth', binWidth, ...
         'numFolds', numFolds, ...
         'fitAll', fitAll, ...
         'xDims_grid', xDims_grid, ...
         'yDims', yDims, ...
         'rGroups', rGroups,...
         'segLength', segLength, ...
         'init_method', init_method, ...
         'learnDelays', learnDelays, ...
         'maxIters', maxIters, ...
         'freqLL', freqLL, ...
         'freqParam', freqParam, ...
         'minVarFrac', minVarFrac, ...
         'parallelize', false, ...
         'randomSeed', randomSeed, ...
         'overwriteExisting', overwriteExisting, ...
         'saveData', saveData);
