% fit_mdlag_sim2.m
%
% Description: This script fits mDLAG models for Simulation 2.
%
% Author: 
%     Evren Gokcen    egokcen@cmu.edu
%

%% Set up script parameters

set_consts_mdlag_sim2;

%% Fit mDLAG model

% Load synthetic data and ground truth
currDataFile = sprintf('%s/%s', dataDir, dataFile);
ws = load(currDataFile);

% Initialize model
initParams = init_mdlag(ws.seqTrue, ...
                        yDims, ...
                        xDim_fit, ...
                        binWidth,...
                        'prior', prior, ...
                        'randomSeed', randomSeed, ...
                        'saveCcov', saveCcov);
                    
% Fit model
[estParams,~,trackedParams,flags] ...
    = em_mdlag(initParams, ...
               ws.seqTrue, ...
               xDim_fit, ...
               'prior', prior, ...
               'tol', tol, ...
               'maxIters', maxIters, ...
               'freqLB', freqLB, ...
               'freqParam', freqParam, ...
               'learnDelays', learnDelays, ...
               'verbose', verbose, ...
               'minVarFrac', minVarFrac, ...
               'maxDelayFrac', maxDelayFrac, ...
               'maxTauFrac', maxTauFrac, ...
               'pruneX', pruneX, ...
               'saveXcov', saveXcov, ...
               'saveCcov', saveCcov);

% Save results 
currSaveDir = sprintf('%s', resultDir);
if isfolder(currSaveDir)
    fprintf('Using existing directory %s...\n', currSaveDir);
else
    fprintf('Making directory %s...\n', currSaveDir);
    mkdir(currSaveDir);
end
currSaveFile = sprintf('%s/mdlag_results_sim2.mat', currSaveDir);
save(currSaveFile, 'estParams', 'trackedParams', 'flags');
      